package github

import (
	"fmt"
	"strings"

	"go.klarlabs.de/coverctl/internal/application"
	"go.klarlabs.de/coverctl/internal/domain"
)

// FormatCoverageComment generates a markdown comment for a PR.
func FormatCoverageComment(result domain.Result, comparison *application.CompareResult) string {
	var b strings.Builder

	// Marker for finding/updating comment
	b.WriteString(CommentMarker)
	b.WriteString("\n")

	// Header
	b.WriteString("## Coverage Report\n\n")

	// Status indicator
	if result.Passed {
		b.WriteString(":white_check_mark: **Coverage check passed**\n\n")
	} else {
		b.WriteString(":x: **Coverage check failed**\n\n")
	}

	// Overall coverage table
	var totalCovered, totalStatements int
	for _, d := range result.Domains {
		totalCovered += d.Covered
		totalStatements += d.Total
	}
	overallPercent := 0.0
	if totalStatements > 0 {
		overallPercent = float64(totalCovered) / float64(totalStatements) * 100
	}

	b.WriteString("| Metric | Value |")
	if comparison != nil {
		b.WriteString(" Change |")
	}
	b.WriteString("\n")

	b.WriteString("|--------|-------|")
	if comparison != nil {
		b.WriteString("--------|")
	}
	b.WriteString("\n")

	b.WriteString(fmt.Sprintf("| Overall | %.1f%% |", overallPercent))
	if comparison != nil {
		b.WriteString(fmt.Sprintf(" %s |", formatDelta(comparison.Delta)))
	}
	b.WriteString("\n\n")

	// Domain coverage table
	if len(result.Domains) > 0 {
		b.WriteString("### Domain Coverage\n\n")
		b.WriteString("| Domain | Coverage | Status |")
		if comparison != nil && len(comparison.DomainDeltas) > 0 {
			b.WriteString(" Change |")
		}
		b.WriteString("\n")

		b.WriteString("|--------|----------|--------|")
		if comparison != nil && len(comparison.DomainDeltas) > 0 {
			b.WriteString("--------|")
		}
		b.WriteString("\n")

		for _, d := range result.Domains {
			var statusIcon string
			switch d.Status {
			case domain.StatusFail:
				statusIcon = ":x:"
			case domain.StatusWarn:
				statusIcon = ":warning:"
			default:
				statusIcon = ":white_check_mark:"
			}

			b.WriteString(fmt.Sprintf("| %s | %.1f%% | %s |", d.Domain, d.Percent, statusIcon))
			if comparison != nil && len(comparison.DomainDeltas) > 0 {
				if delta, ok := comparison.DomainDeltas[d.Domain]; ok {
					b.WriteString(fmt.Sprintf(" %s |", formatDelta(delta)))
				} else {
					b.WriteString(" - |")
				}
			}
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}

	// Changed files details (if comparison provided)
	if comparison != nil && (len(comparison.Improved) > 0 || len(comparison.Regressed) > 0) {
		b.WriteString("<details><summary>Changed Files</summary>\n\n")

		if len(comparison.Improved) > 0 {
			b.WriteString("#### Improved\n\n")
			b.WriteString("| File | Before | After | Change |\n")
			b.WriteString("|------|--------|-------|--------|\n")
			for _, f := range comparison.Improved {
				if len(f.File) > 60 {
					f.File = "..." + f.File[len(f.File)-57:]
				}
				b.WriteString(fmt.Sprintf("| %s | %.1f%% | %.1f%% | %s |\n",
					f.File, f.BasePct, f.HeadPct, formatDelta(f.Delta)))
			}
			b.WriteString("\n")
		}

		if len(comparison.Regressed) > 0 {
			b.WriteString("#### Regressed\n\n")
			b.WriteString("| File | Before | After | Change |\n")
			b.WriteString("|------|--------|-------|--------|\n")
			for _, f := range comparison.Regressed {
				if len(f.File) > 60 {
					f.File = "..." + f.File[len(f.File)-57:]
				}
				b.WriteString(fmt.Sprintf("| %s | %.1f%% | %.1f%% | %s |\n",
					f.File, f.BasePct, f.HeadPct, formatDelta(f.Delta)))
			}
			b.WriteString("\n")
		}

		b.WriteString("</details>\n\n")
	}

	// Warnings
	if len(result.Warnings) > 0 {
		b.WriteString("<details><summary>Warnings</summary>\n\n")
		for _, w := range result.Warnings {
			b.WriteString(fmt.Sprintf("- %s\n", w))
		}
		b.WriteString("\n</details>\n\n")
	}

	// Footer
	b.WriteString("---\n")
	b.WriteString("*Generated by [coverctl](https://github.com/klarlabs-studio/coverctl)*\n")

	return b.String()
}

// formatDelta formats a coverage delta with sign and color indicator.
func formatDelta(delta float64) string {
	if delta > 0.1 {
		return fmt.Sprintf(":arrow_up: +%.1f%%", delta)
	} else if delta < -0.1 {
		return fmt.Sprintf(":arrow_down: %.1f%%", delta)
	}
	return "~0%"
}
