package github

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.klarlabs.de/coverctl/internal/application"
	"go.klarlabs.de/coverctl/internal/domain"
)

func TestFormatDelta(t *testing.T) {
	tests := []struct {
		name     string
		delta    float64
		expected string
	}{
		{
			name:     "positive delta shows up arrow",
			delta:    5.2,
			expected: ":arrow_up: +5.2%",
		},
		{
			name:     "small positive delta above threshold shows up arrow",
			delta:    0.2,
			expected: ":arrow_up: +0.2%",
		},
		{
			name:     "negative delta shows down arrow",
			delta:    -3.5,
			expected: ":arrow_down: -3.5%",
		},
		{
			name:     "small negative delta below threshold shows down arrow",
			delta:    -0.2,
			expected: ":arrow_down: -0.2%",
		},
		{
			name:     "zero delta shows approximately zero",
			delta:    0.0,
			expected: "~0%",
		},
		{
			name:     "positive near-zero delta within threshold shows approximately zero",
			delta:    0.1,
			expected: "~0%",
		},
		{
			name:     "negative near-zero delta within threshold shows approximately zero",
			delta:    -0.1,
			expected: "~0%",
		},
		{
			name:     "exact positive threshold boundary shows approximately zero",
			delta:    0.1,
			expected: "~0%",
		},
		{
			name:     "exact negative threshold boundary shows approximately zero",
			delta:    -0.1,
			expected: "~0%",
		},
		{
			name:     "large positive delta",
			delta:    25.0,
			expected: ":arrow_up: +25.0%",
		},
		{
			name:     "large negative delta",
			delta:    -42.7,
			expected: ":arrow_down: -42.7%",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := formatDelta(tt.delta)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestFormatCoverageComment(t *testing.T) {
	t.Run("starts with comment marker", func(t *testing.T) {
		result := domain.Result{Passed: true}
		comment := FormatCoverageComment(result, nil)
		assert.True(t, strings.HasPrefix(comment, CommentMarker),
			"comment must start with the marker for finding/updating")
		assert.Contains(t, comment, "<!-- coverctl-coverage-report -->")
	})

	t.Run("ends with footer", func(t *testing.T) {
		result := domain.Result{Passed: true}
		comment := FormatCoverageComment(result, nil)
		assert.Contains(t, comment, "*Generated by [coverctl](https://github.com/klarlabs-studio/coverctl)*")
	})

	t.Run("passing result without comparison", func(t *testing.T) {
		result := domain.Result{
			Passed: true,
			Domains: []domain.DomainResult{
				{Domain: "core", Covered: 80, Total: 100, Percent: 80.0, Required: 70.0, Status: domain.StatusPass},
			},
		}
		comment := FormatCoverageComment(result, nil)

		assert.Contains(t, comment, ":white_check_mark: **Coverage check passed**")
		assert.NotContains(t, comment, ":x:")
		assert.Contains(t, comment, "| Overall | 80.0% |")
		// No Change column when comparison is nil
		assert.NotContains(t, comment, "Change |")
	})

	t.Run("failing result without comparison", func(t *testing.T) {
		result := domain.Result{
			Passed: false,
			Domains: []domain.DomainResult{
				{Domain: "core", Covered: 30, Total: 100, Percent: 30.0, Required: 70.0, Status: domain.StatusFail},
			},
		}
		comment := FormatCoverageComment(result, nil)

		assert.Contains(t, comment, ":x: **Coverage check failed**")
		assert.NotContains(t, comment, ":white_check_mark: **Coverage check passed**")
		assert.Contains(t, comment, "| Overall | 30.0% |")
	})

	t.Run("result with comparison includes delta column", func(t *testing.T) {
		result := domain.Result{
			Passed: true,
			Domains: []domain.DomainResult{
				{Domain: "core", Covered: 85, Total: 100, Percent: 85.0, Required: 70.0, Status: domain.StatusPass},
			},
		}
		comparison := &application.CompareResult{
			Delta:        5.0,
			DomainDeltas: map[string]float64{"core": 5.0},
		}
		comment := FormatCoverageComment(result, comparison)

		assert.Contains(t, comment, "Change |")
		assert.Contains(t, comment, ":arrow_up: +5.0%")
	})

	t.Run("result with domain coverage table", func(t *testing.T) {
		result := domain.Result{
			Passed: false,
			Domains: []domain.DomainResult{
				{Domain: "core", Covered: 90, Total: 100, Percent: 90.0, Required: 80.0, Status: domain.StatusPass},
				{Domain: "api", Covered: 40, Total: 100, Percent: 40.0, Required: 60.0, Status: domain.StatusFail},
				{Domain: "utils", Covered: 55, Total: 100, Percent: 55.0, Required: 50.0, Status: domain.StatusWarn},
			},
		}
		comment := FormatCoverageComment(result, nil)

		assert.Contains(t, comment, "### Domain Coverage")
		assert.Contains(t, comment, "| core | 90.0% | :white_check_mark: |")
		assert.Contains(t, comment, "| api | 40.0% | :x: |")
		assert.Contains(t, comment, "| utils | 55.0% | :warning: |")
	})

	t.Run("result with domain deltas", func(t *testing.T) {
		result := domain.Result{
			Passed: true,
			Domains: []domain.DomainResult{
				{Domain: "core", Covered: 85, Total: 100, Percent: 85.0, Required: 70.0, Status: domain.StatusPass},
				{Domain: "api", Covered: 60, Total: 100, Percent: 60.0, Required: 50.0, Status: domain.StatusPass},
			},
		}
		comparison := &application.CompareResult{
			Delta: 3.0,
			DomainDeltas: map[string]float64{
				"core": 5.0,
				"api":  -2.0,
			},
		}
		comment := FormatCoverageComment(result, comparison)

		assert.Contains(t, comment, "| core | 85.0% | :white_check_mark: | :arrow_up: +5.0% |")
		assert.Contains(t, comment, "| api | 60.0% | :white_check_mark: | :arrow_down: -2.0% |")
	})

	t.Run("domain without delta shows dash", func(t *testing.T) {
		result := domain.Result{
			Passed: true,
			Domains: []domain.DomainResult{
				{Domain: "core", Covered: 85, Total: 100, Percent: 85.0, Required: 70.0, Status: domain.StatusPass},
				{Domain: "new-domain", Covered: 50, Total: 100, Percent: 50.0, Required: 40.0, Status: domain.StatusPass},
			},
		}
		comparison := &application.CompareResult{
			Delta:        3.0,
			DomainDeltas: map[string]float64{"core": 3.0},
		}
		comment := FormatCoverageComment(result, comparison)

		assert.Contains(t, comment, "| new-domain | 50.0% | :white_check_mark: | - |")
	})

	t.Run("comparison with improved files", func(t *testing.T) {
		result := domain.Result{Passed: true}
		comparison := &application.CompareResult{
			Delta: 5.0,
			Improved: []application.FileDelta{
				{File: "pkg/service.go", BasePct: 60.0, HeadPct: 85.0, Delta: 25.0},
				{File: "pkg/handler.go", BasePct: 40.0, HeadPct: 55.0, Delta: 15.0},
			},
		}
		comment := FormatCoverageComment(result, comparison)

		assert.Contains(t, comment, "<details><summary>Changed Files</summary>")
		assert.Contains(t, comment, "#### Improved")
		assert.Contains(t, comment, "| pkg/service.go | 60.0% | 85.0% | :arrow_up: +25.0% |")
		assert.Contains(t, comment, "| pkg/handler.go | 40.0% | 55.0% | :arrow_up: +15.0% |")
	})

	t.Run("comparison with regressed files", func(t *testing.T) {
		result := domain.Result{Passed: true}
		comparison := &application.CompareResult{
			Delta: -3.0,
			Regressed: []application.FileDelta{
				{File: "pkg/model.go", BasePct: 90.0, HeadPct: 70.0, Delta: -20.0},
			},
		}
		comment := FormatCoverageComment(result, comparison)

		assert.Contains(t, comment, "#### Regressed")
		assert.Contains(t, comment, "| pkg/model.go | 90.0% | 70.0% | :arrow_down: -20.0% |")
	})

	t.Run("comparison with both improved and regressed files", func(t *testing.T) {
		result := domain.Result{Passed: true}
		comparison := &application.CompareResult{
			Delta: 1.0,
			Improved: []application.FileDelta{
				{File: "pkg/a.go", BasePct: 50.0, HeadPct: 80.0, Delta: 30.0},
			},
			Regressed: []application.FileDelta{
				{File: "pkg/b.go", BasePct: 90.0, HeadPct: 75.0, Delta: -15.0},
			},
		}
		comment := FormatCoverageComment(result, comparison)

		assert.Contains(t, comment, "#### Improved")
		assert.Contains(t, comment, "#### Regressed")
		assert.Contains(t, comment, "</details>")
	})

	t.Run("no changed files section when comparison has no improved or regressed", func(t *testing.T) {
		result := domain.Result{Passed: true}
		comparison := &application.CompareResult{
			Delta:     0.0,
			Unchanged: 10,
		}
		comment := FormatCoverageComment(result, comparison)

		assert.NotContains(t, comment, "Changed Files")
		assert.NotContains(t, comment, "#### Improved")
		assert.NotContains(t, comment, "#### Regressed")
	})

	t.Run("long file names get truncated to 60 chars with ellipsis prefix", func(t *testing.T) {
		longFile := "internal/infrastructure/github/very/deeply/nested/package/with/long/path/service.go"
		require.Greater(t, len(longFile), 60, "test file name must be longer than 60 chars")

		result := domain.Result{Passed: true}
		comparison := &application.CompareResult{
			Delta: 5.0,
			Improved: []application.FileDelta{
				{File: longFile, BasePct: 50.0, HeadPct: 80.0, Delta: 30.0},
			},
		}
		comment := FormatCoverageComment(result, comparison)

		// The truncated file should start with "..." and be exactly 60 chars
		expectedTruncated := "..." + longFile[len(longFile)-57:]
		assert.Contains(t, comment, expectedTruncated)
		assert.Len(t, expectedTruncated, 60)
		assert.NotContains(t, comment, longFile)
	})

	t.Run("file names at exactly 60 chars are not truncated", func(t *testing.T) {
		// Build a file name that is exactly 60 characters
		file60 := strings.Repeat("a", 57) + ".go"
		require.Len(t, file60, 60, "test file name must be exactly 60 chars")

		result := domain.Result{Passed: true}
		comparison := &application.CompareResult{
			Delta: 2.0,
			Improved: []application.FileDelta{
				{File: file60, BasePct: 50.0, HeadPct: 70.0, Delta: 20.0},
			},
		}
		comment := FormatCoverageComment(result, comparison)

		assert.Contains(t, comment, file60)
		assert.NotContains(t, comment, "..."+file60)
	})

	t.Run("result with warnings", func(t *testing.T) {
		result := domain.Result{
			Passed:   true,
			Warnings: []string{"No files matched domain 'legacy'", "Profile merge had conflicts"},
		}
		comment := FormatCoverageComment(result, nil)

		assert.Contains(t, comment, "<details><summary>Warnings</summary>")
		assert.Contains(t, comment, "- No files matched domain 'legacy'")
		assert.Contains(t, comment, "- Profile merge had conflicts")
		assert.Contains(t, comment, "</details>")
	})

	t.Run("no warnings section when no warnings present", func(t *testing.T) {
		result := domain.Result{Passed: true}
		comment := FormatCoverageComment(result, nil)

		assert.NotContains(t, comment, "Warnings</summary>")
	})

	t.Run("empty domains yields zero overall coverage", func(t *testing.T) {
		result := domain.Result{Passed: true}
		comment := FormatCoverageComment(result, nil)

		assert.Contains(t, comment, "| Overall | 0.0% |")
		assert.NotContains(t, comment, "### Domain Coverage")
	})

	t.Run("overall coverage is calculated from domain totals", func(t *testing.T) {
		result := domain.Result{
			Passed: true,
			Domains: []domain.DomainResult{
				{Domain: "a", Covered: 75, Total: 100, Percent: 75.0, Required: 50.0, Status: domain.StatusPass},
				{Domain: "b", Covered: 25, Total: 100, Percent: 25.0, Required: 20.0, Status: domain.StatusPass},
			},
		}
		comment := FormatCoverageComment(result, nil)

		// Overall = (75 + 25) / (100 + 100) * 100 = 50.0%
		assert.Contains(t, comment, "| Overall | 50.0% |")
	})

	t.Run("comparison with empty domain deltas omits change column in domain table", func(t *testing.T) {
		result := domain.Result{
			Passed: true,
			Domains: []domain.DomainResult{
				{Domain: "core", Covered: 80, Total: 100, Percent: 80.0, Required: 70.0, Status: domain.StatusPass},
			},
		}
		comparison := &application.CompareResult{
			Delta:        2.0,
			DomainDeltas: map[string]float64{},
		}
		comment := FormatCoverageComment(result, comparison)

		// The overall table should have a Change column
		lines := strings.Split(comment, "\n")
		var overallLine string
		for _, line := range lines {
			if strings.Contains(line, "| Overall |") {
				overallLine = line
				break
			}
		}
		require.NotEmpty(t, overallLine)
		assert.Contains(t, overallLine, ":arrow_up: +2.0%")

		// Domain table should NOT have a Change column since DomainDeltas is empty
		var domainCoreLine string
		for _, line := range lines {
			if strings.Contains(line, "| core |") {
				domainCoreLine = line
				break
			}
		}
		require.NotEmpty(t, domainCoreLine)
		// Only 3 pipe-separated columns (Domain, Coverage, Status), not 4
		parts := strings.Split(strings.Trim(domainCoreLine, "|"), "|")
		assert.Len(t, parts, 3, "domain row should have 3 columns when domain deltas are empty")
	})

	t.Run("full comment structure ordering", func(t *testing.T) {
		result := domain.Result{
			Passed: true,
			Domains: []domain.DomainResult{
				{Domain: "core", Covered: 80, Total: 100, Percent: 80.0, Required: 70.0, Status: domain.StatusPass},
			},
			Warnings: []string{"something"},
		}
		comparison := &application.CompareResult{
			Delta:        2.0,
			DomainDeltas: map[string]float64{"core": 2.0},
			Improved: []application.FileDelta{
				{File: "f.go", BasePct: 50.0, HeadPct: 70.0, Delta: 20.0},
			},
		}
		comment := FormatCoverageComment(result, comparison)

		markerIdx := strings.Index(comment, CommentMarker)
		headerIdx := strings.Index(comment, "## Coverage Report")
		statusIdx := strings.Index(comment, ":white_check_mark:")
		overallIdx := strings.Index(comment, "| Overall |")
		domainIdx := strings.Index(comment, "### Domain Coverage")
		changedIdx := strings.Index(comment, "Changed Files")
		warningIdx := strings.Index(comment, "Warnings")
		footerIdx := strings.Index(comment, "Generated by")

		assert.Less(t, markerIdx, headerIdx, "marker before header")
		assert.Less(t, headerIdx, statusIdx, "header before status")
		assert.Less(t, statusIdx, overallIdx, "status before overall")
		assert.Less(t, overallIdx, domainIdx, "overall before domain coverage")
		assert.Less(t, domainIdx, changedIdx, "domain coverage before changed files")
		assert.Less(t, changedIdx, warningIdx, "changed files before warnings")
		assert.Less(t, warningIdx, footerIdx, "warnings before footer")
	})
}
